2021-07-22 11:10:42,215 INFO: Microblog startup [in C:\GIT\Budget_planner\app\__init__.py:28]
2021-07-22 11:11:53,609 INFO: Microblog startup [in C:\GIT\Budget_planner\app\__init__.py:28]
2021-07-22 11:19:03,002 INFO: Microblog startup [in C:\GIT\Budget_planner\app\__init__.py:28]
2021-07-22 11:25:27,595 INFO: Microblog startup [in C:\GIT\Budget_planner\app\__init__.py:28]
2021-08-08 12:46:23,881 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-08 12:46:38,616 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-09 19:31:27,177 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-09 19:36:32,167 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-09 19:37:00,207 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-09 19:38:28,654 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-09 19:39:56,781 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-09 19:43:19,198 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-15 10:33:30,598 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-15 10:34:20,670 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-15 10:34:24,502 ERROR: Exception on /add [GET] [in D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'add' did not return a valid response. The function either returned None or ended without a return statement.
2021-08-15 10:34:25,500 ERROR: Exception on /add [GET] [in D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'add' did not return a valid response. The function either returned None or ended without a return statement.
2021-08-15 10:34:26,178 ERROR: Exception on /add [GET] [in D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'add' did not return a valid response. The function either returned None or ended without a return statement.
2021-08-15 10:34:26,813 ERROR: Exception on /add [GET] [in D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'add' did not return a valid response. The function either returned None or ended without a return statement.
2021-08-15 10:37:19,397 ERROR: Exception on /add [GET] [in D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1698, in make_response
    raise TypeError(
TypeError: The view function for 'add' did not return a valid response. The function either returned None or ended without a return statement.
2021-08-15 10:37:23,586 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-15 10:58:00,102 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-15 12:22:37,794 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-15 12:22:48,139 ERROR: Exception on /add [GET] [in D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\GIT\Budget_Planner\app\routes.py", line 75, in add
    return render_template('add.html')
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\GIT\Budget_Planner\app\templates\add.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "D:\GIT\Budget_Planner\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "D:\GIT\Budget_Planner\app\templates\base.html", line 35, in block 'content'
    {% block app_content %}{% endblock %}
  File "D:\GIT\Budget_Planner\app\templates\add.html", line 8, in block 'app_content'
    {{ wtf.quick_form(form) }}
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\jinja2\runtime.py", line 828, in _invoke
    rv = self._func(*arguments)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 200, in template
    {{ form.hidden_tag() }}
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-08-15 12:24:26,047 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
