2021-08-18 19:37:48,322 ERROR: Exception on /add [POST] [in D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1710, in make_response
    rv = self.response_class(rv, status=status, headers=headers)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\werkzeug\wrappers\response.py", line 181, in __init__
    super().__init__(
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\werkzeug\sansio\response.py", line 128, in __init__
    self.headers = Headers(headers)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\werkzeug\datastructures.py", line 882, in __init__
    self.extend(defaults)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\werkzeug\datastructures.py", line 1019, in extend
    for key, value in iter_multi_items(args[0]):
ValueError: not enough values to unpack (expected 2, got 1)
2021-08-18 19:37:54,971 ERROR: Exception on /add [POST] [in D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1535, in finalize_request
    response = self.make_response(rv)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1710, in make_response
    rv = self.response_class(rv, status=status, headers=headers)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\werkzeug\wrappers\response.py", line 181, in __init__
    super().__init__(
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\werkzeug\sansio\response.py", line 128, in __init__
    self.headers = Headers(headers)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\werkzeug\datastructures.py", line 882, in __init__
    self.extend(defaults)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\werkzeug\datastructures.py", line 1019, in extend
    for key, value in iter_multi_items(args[0]):
ValueError: not enough values to unpack (expected 2, got 1)
2021-08-18 19:38:02,016 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 19:38:37,639 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 19:39:23,639 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 19:39:48,017 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 19:40:25,642 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 19:41:08,988 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 19:41:25,247 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 19:42:18,747 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 19:42:20,825 ERROR: Exception on /add [POST] [in D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\GIT\Budget_Planner\app\routes.py", line 84, in add_post
    return {{ sname }} - {{ fname }}
TypeError: unhashable type: 'set'
2021-08-18 19:42:27,742 ERROR: Exception on /add [POST] [in D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\GIT\Budget_Planner\app\routes.py", line 84, in add_post
    return {{ sname }} - {{ fname }}
TypeError: unhashable type: 'set'
2021-08-18 19:43:20,974 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 19:43:24,041 ERROR: Exception on /add [POST] [in D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\GIT\Budget_Planner\app\routes.py", line 84, in add_post
    return {{ sname }} - {{ fname }}
TypeError: unhashable type: 'set'
2021-08-18 19:43:30,483 ERROR: Exception on /add [POST] [in D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\GIT\Budget_Planner\venv2\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\GIT\Budget_Planner\app\routes.py", line 84, in add_post
    return {{ sname }} - {{ fname }}
TypeError: unhashable type: 'set'
2021-08-18 19:44:02,151 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 19:44:58,734 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 19:46:03,918 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 19:46:44,386 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 19:50:28,544 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:22:13,149 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:22:24,112 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:22:24,112 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:22:45,443 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:22:45,443 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:22:45,443 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:27:06,519 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:28:35,269 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:29:14,784 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:29:29,942 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:30:46,435 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:32:11,752 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:34:25,641 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:38:46,391 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:42:01,688 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:43:12,160 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:46:02,285 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 20:52:07,387 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 21:01:21,440 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 21:01:31,405 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 21:05:27,849 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 21:29:07,986 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 21:31:19,443 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 21:33:19,974 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 21:36:16,681 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
2021-08-18 21:37:03,268 INFO: Microblog startup [in D:\GIT\Budget_Planner\app\__init__.py:30]
